### ISSUE TITLE
Compatibility issues with latest Oban release (2.18.3)

### ISSUE THREAD

**Issue by MateusAquino** [oban-bg/oban#1166]
### Report

I'm not sure if it's related to using an older version of Elixir or not, but since this last update our CI is breaking and we are not able to update Oban's version:

https://github.com/oban-bg/oban/blob/696df17de5e0af966a6b4cbee9b14f4e9a7a2c8e/lib/oban/nursery.ex#L27

### Environment

- Oban Version: 2.18.3 (Free)
- PostgreSQL Version: 13-alpine
- Elixir & Erlang/OTP Versions: Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Current Behavior

Stacktrace from CI:

```rust
** (Mix) Could not start application my_application: MyApplication.Application.start(:normal, []) returned an error: shutdown: failed to start child: Oban
    ** (EXIT) shutdown: failed to start child: {:via, Registry, {Oban.Registry, {Oban, Oban.Nursery}}}
        ** (EXIT) shutdown: failed to start child: {Oban.Registry, {Oban, Foreman}}
            ** (EXIT) an exception was raised:
                ** (ArgumentError) expected :strategy option to be given
                    (elixir 1.13.4) lib/dynamic_supervisor.ex:516: DynamicSupervisor.init/1
                    (elixir 1.13.4) lib/dynamic_supervisor.ex:258: DynamicSupervisor.start_link/1
                    (stdlib 4.3.1.5) supervisor.erl:420: :supervisor.do_start_child_i/3
                    (stdlib 4.3.1.5) supervisor.erl:406: :supervisor.do_start_child/2
                    (stdlib 4.3.1.5) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
                    (stdlib 4.3.1.5) supervisor.erl:1273: :supervisor.children_map/4
                    (stdlib 4.3.1.5) supervisor.erl:350: :supervisor.init_children/2
                    (stdlib 4.3.1.5) gen_server.erl:851: :gen_server.init_it/2
```

### Expected Behavior

One minor version behind the application would start just fine.

In application.ex we are using `strategy: :one_for_one` and starting Oban normally:

```elixir
    {Oban, Application.fetch_env!(:my_application, Oban)}
```

Config:

```elixir
config :my_application, Oban,
  repo: MyApplication.Repo,
  plugins: [
    {
      Oban.Plugins.Cron,
      crontab: [
          # ...
      ]
    }
  ],
  queues: [
    # ...
  ]
```

We are also using latest migration version:

```elixir
Oban.Migrations.up(version: 11)
```

**Comment by sorentwo** [comment]
This is because you're using an older Elixir version. Oban v2.18 requires Elixir 1.14+ (incorrect in the README, but stated in [mix.exs](https://github.com/oban-bg/oban/blob/main/mix.exs#L11)). We'll update the README to reflect the correct minimum for v2.18.

You'll need to either upgrade Elixir, or stick to Oban v2.17 (upgrading Elixir is highly recommended)
